apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    type: nginx-app
spec:
  containers:
  - name: hello1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    type: nginx-app
spec:
  containers:
  - name: hello2
    image: nginx:1.14.2
    ports:
    - containerPort: 80
