apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    type: nginx-app
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      type: nginx-app
  template:
    metadata:
      labels:
        type: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
