apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx-app
    spec:
      containers:
      - name: {{ .Release.Name }}-nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http-web-svc
        volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: www-data
        configMap:
          name: {{ .Release.Name }}-nginx-www-cm