apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-nginx-ingress
spec:
  rules:
  - host: {{ .Values.domain | quote }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-nginx-service
            port:
              name: http-port