apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-nginx-app
  ports:
  - name: http-port
    protocol: TCP
    port: 9000
    targetPort: http-web-svc